MAKEDIR=../../config
include $(MAKEDIR)/make.app


DESCRIPTION=gui_test
APPNAME=gui_test
INSTALLPATH=$(BASE)/applications


EXTRA_LDFLAGS=$(LIBRARYROOT)/libgui.a $(LIBRARYROOT)/libcomms.a $(LIBRARYROOT)/libdevfs.a $(LIBRARYROOT)/libsmk.a

