MAKEDIR=../../config
include $(MAKEDIR)/make.app

DESCRIPTION=shell application
APPNAME=shell
INSTALLPATH=$(BASE)/applications
CODE="C"
FILES=*.c

	
EXTRA_LDFLAGS=$(LIBRARYROOT)/libunix.a $(LIBRARYROOT)/libvfs.a




